# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: cc4434ba8f6fbd82c47b858ab9c511f7c01e3d5897809b906274f7a0f0a27b7cb6f25e3b39fadfe67c7cd2b298c8a59448c711d16ac65026c7790326dd93443f

test:
  secret_key_base: 3076d6133951df588d6e2ecd75f732ba69f8f175a3cdca34dca5370c246f00c32baacd1175e88945ba66ccda0b87bcab1fc6d51adebe5768c5f678a9bd084411

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
